// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoEPjvj-U-PV669CdQhPYdJSqJFBL-4M',
    appId: '1:129025358734:web:01bd5c24664020004ec2df',
    messagingSenderId: '129025358734',
    projectId: 'fir-gridview-projects',
    authDomain: 'fir-gridview-projects.firebaseapp.com',
    storageBucket: 'fir-gridview-projects.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHDJQAqqIa4-of5gi6sUaZSWYTdRvCsw',
    appId: '1:129025358734:android:75644b8660d71da14ec2df',
    messagingSenderId: '129025358734',
    projectId: 'fir-gridview-projects',
    storageBucket: 'fir-gridview-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWbLl_xvNfMWsbcm2AH9Oj_nV84ij6A0',
    appId: '1:129025358734:ios:ba2461bdb34ed0cb4ec2df',
    messagingSenderId: '129025358734',
    projectId: 'fir-gridview-projects',
    storageBucket: 'fir-gridview-projects.appspot.com',
    iosBundleId: 'com.example.firebaseGridviewProjects',
  );
}
